// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OLTPDatabaseCore.DatabaseContext;

#nullable disable

namespace DataVaultDb.Migrations
{
    [DbContext(typeof(DWHDbContext))]
    partial class DWHDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataVaultDb.Models.CompanyHub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BKHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LoadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompanyHub");
                });

            modelBuilder.Entity("DataVaultDb.Models.CompanySat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyHubId")
                        .HasColumnType("int")
                        .HasColumnName("company_hub_id");

                    b.Property<DateTime>("LoadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyHubId");

                    b.ToTable("CompanySat");
                });

            modelBuilder.Entity("DataVaultDb.Models.GoodsHub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BKHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LoadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GoodsHub");
                });

            modelBuilder.Entity("DataVaultDb.Models.GoodsSat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GoodsHubId")
                        .HasColumnType("int")
                        .HasColumnName("goods_hub_id");

                    b.Property<DateTime>("LoadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<double>("SalePrice")
                        .HasColumnType("float")
                        .HasColumnName("sale_price");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GoodsHubId");

                    b.ToTable("GoodsSat");
                });

            modelBuilder.Entity("DataVaultDb.Models.OrderCompanyLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyHubId")
                        .HasColumnType("int")
                        .HasColumnName("company_hub_id");

                    b.Property<DateTime>("LoadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderHubId")
                        .HasColumnType("int")
                        .HasColumnName("order_hub_id");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyHubId");

                    b.HasIndex("OrderHubId");

                    b.ToTable("OrderCompanyLink");
                });

            modelBuilder.Entity("DataVaultDb.Models.OrderCompanyLinkSat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LoadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderCompanyLinkId")
                        .HasColumnType("int")
                        .HasColumnName("order_company_link_id");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderCompanyLinkId");

                    b.ToTable("OrderCompanyLinkSat");
                });

            modelBuilder.Entity("DataVaultDb.Models.OrderGoodsLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GoodsHubId")
                        .HasColumnType("int")
                        .HasColumnName("goods_hub_id");

                    b.Property<DateTime>("LoadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderHubId")
                        .HasColumnType("int")
                        .HasColumnName("order_hub_id");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GoodsHubId");

                    b.HasIndex("OrderHubId");

                    b.ToTable("OrderGoodsLink");
                });

            modelBuilder.Entity("DataVaultDb.Models.OrderGoodsLinkSat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LoadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderGoodsLinkId")
                        .HasColumnType("int")
                        .HasColumnName("order_goods_link_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderGoodsLinkId");

                    b.ToTable("OrderGoodsLinkSat");
                });

            modelBuilder.Entity("DataVaultDb.Models.OrderHub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BKHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LoadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderHub");
                });

            modelBuilder.Entity("DataVaultDb.Models.OrderSat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("LoadDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderHubId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShipmentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("shipment_date");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("OrderHubId");

                    b.ToTable("OrderSat");
                });

            modelBuilder.Entity("DataVaultDb.Models.CompanySat", b =>
                {
                    b.HasOne("DataVaultDb.Models.CompanyHub", "CompanyHub")
                        .WithMany("CompanySats")
                        .HasForeignKey("CompanyHubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyHub");
                });

            modelBuilder.Entity("DataVaultDb.Models.GoodsSat", b =>
                {
                    b.HasOne("DataVaultDb.Models.GoodsHub", "GoodsHub")
                        .WithMany("GoodsSats")
                        .HasForeignKey("GoodsHubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoodsHub");
                });

            modelBuilder.Entity("DataVaultDb.Models.OrderCompanyLink", b =>
                {
                    b.HasOne("DataVaultDb.Models.CompanyHub", "CompanyHub")
                        .WithMany()
                        .HasForeignKey("CompanyHubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataVaultDb.Models.OrderHub", "OrderHub")
                        .WithMany()
                        .HasForeignKey("OrderHubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyHub");

                    b.Navigation("OrderHub");
                });

            modelBuilder.Entity("DataVaultDb.Models.OrderCompanyLinkSat", b =>
                {
                    b.HasOne("DataVaultDb.Models.OrderCompanyLink", "OrderCompanyLink")
                        .WithMany("OrderCompanyLinkSats")
                        .HasForeignKey("OrderCompanyLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderCompanyLink");
                });

            modelBuilder.Entity("DataVaultDb.Models.OrderGoodsLink", b =>
                {
                    b.HasOne("DataVaultDb.Models.GoodsHub", "GoodsHub")
                        .WithMany()
                        .HasForeignKey("GoodsHubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataVaultDb.Models.OrderHub", "OrderHub")
                        .WithMany()
                        .HasForeignKey("OrderHubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoodsHub");

                    b.Navigation("OrderHub");
                });

            modelBuilder.Entity("DataVaultDb.Models.OrderGoodsLinkSat", b =>
                {
                    b.HasOne("DataVaultDb.Models.OrderGoodsLink", "OrderGoodsLink")
                        .WithMany("OrderGoodsLinkSats")
                        .HasForeignKey("OrderGoodsLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderGoodsLink");
                });

            modelBuilder.Entity("DataVaultDb.Models.OrderSat", b =>
                {
                    b.HasOne("DataVaultDb.Models.OrderHub", "OrderHub")
                        .WithMany("OrderSats")
                        .HasForeignKey("OrderHubId");

                    b.Navigation("OrderHub");
                });

            modelBuilder.Entity("DataVaultDb.Models.CompanyHub", b =>
                {
                    b.Navigation("CompanySats");
                });

            modelBuilder.Entity("DataVaultDb.Models.GoodsHub", b =>
                {
                    b.Navigation("GoodsSats");
                });

            modelBuilder.Entity("DataVaultDb.Models.OrderCompanyLink", b =>
                {
                    b.Navigation("OrderCompanyLinkSats");
                });

            modelBuilder.Entity("DataVaultDb.Models.OrderGoodsLink", b =>
                {
                    b.Navigation("OrderGoodsLinkSats");
                });

            modelBuilder.Entity("DataVaultDb.Models.OrderHub", b =>
                {
                    b.Navigation("OrderSats");
                });
#pragma warning restore 612, 618
        }
    }
}
